baseURL = 'https://rouxles.github.io/decal-readings'
languageCode = 'en-us'
title = 'Teaching'
theme = "hugo-book"
enableGitInfo = true
publishDir = "docs"

[params]

    BookTheme = 'auto'
    BookRepo = 'https://github.com/Rouxles/teaching'
    BookSearch = false